### ISSUE TITLE
Where best to change the width of the main article?

### ISSUE THREAD

**Issue by SteveDunn** [google/eleventy-high-performance-blog#91]
Hi,

I would like to make the width of 'article' a little bigger.  I think I've found the place in `main.css`:

``` css
@media (min-width: 37.5em) {
  :root {
    --main-width: calc(37.5em - 3em);
  }
}
```

I'm _guessing_ that's the right place to change it.  It seems to work both locally and when I publish to Netlify.

A couple of points:
1. I understand this isn't an _issue_ per-se, but I thought I'd raise it here as I'm sure others would like to know
2. May I ask _why_ 37.5em was chosen?  It looked a little narrow. The new size of 45.0em looks OK to me on both my desktop and a phone, but I wouldn't want to worsen the reading experience for anyone else

Thankyou for such a fantastic template and thanks in advance for any assistance with this issue.

Steve
